CREATE TABLE CLIENT(
 ID bigint NOT NULL AUTO_INCREMENT,
 NAME VARCHAR(200) CHECK(CHAR_LENGTH(NAME) >= 3),
 primary key(ID)
);
CREATE TABLE PLANET(
 ID VARCHAR(256) CHECK REGEXP_LIKE(ID, '[A-Z0-9]+$'),
 NAME VARCHAR(500) NOT NULL,
 primary key(ID)
);
CREATE TABLE TICKET(
 ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 CREATED_AT timestamp NOT NULL,
 CLIENT_ID BIGINT,
 FROM_PLANET_ID VARCHAR(256),
 TO_PLANET_ID VARCHAR(256),
 FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(ID),
 FOREIGN KEY(FROM_PLANET_ID) REFERENCES PLANET(ID),
 FOREIGN KEY(TO_PLANET_ID) REFERENCES PLANET(ID)
)